version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 7432:7432
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: -p 7432

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8008:8008"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=7432
    command: sh run_web.sh
    depends_on:
      - db

  phppgadmin:
    image: docker.io/bitnami/phppgadmin:7
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT_NUMBER=7432
    ports:
      - '1234:8080'
    depends_on:
      - db
